### ISSUE TITLE
 Remove id from model classes

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#1048]
## Feature Request

The id should not be part of the model classes. The outside world shouldn't know anything about the technical details. Depending on the user application, the id could be a string, uuid or an integer.

Classes:
- `Model\Page(Interface)`
- `Model\Site(Interface)`

**Comment by VincentLanglet** [comment]
I don't consider as an issue the fact to have a `getId()` method in our interface.
- We have this in lot of sonata projects: https://github.com/sonata-project/SonataMediaBundle/blob/4.x/src/Model/GalleryInterface.php#L25-L28 or https://github.com/sonata-project/SonataBlockBundle/blob/4.x/src/Model/BlockInterface.php#L27-L30
- We need an identifier to run a command on a specific page/site https://github.com/sonata-project/SonataPageBundle/blob/488259c77c91f62d07ee4e7656a6f2921f0819e8/src/Command/CleanupSnapshotsCommand.php#L34 or when writing messages.

Also, since it's used everywhere, it's not an easy issue.
The lack of activity in this issue push me to close it.
