### ISSUE TITLE
Remove Sonata Cache

### ISSUE THREAD

**Issue by core23** [sonata-project/SonataPageBundle#1096]
We should use symfony cache instead.

Even the doctrine cache was just deprecated in favor of symfony cache:
https://github.com/doctrine/DoctrineCacheBundle#deprecation-warning

**Comment by eerison** [comment]
@VincentLanglet can you add this in https://github.com/sonata-project/SonataPageBundle/milestone/1

please :)

**Comment by Hanmac** [comment]
I did some brain storming about Removing Sonata Cache(Bundle) from Page Bundle.

* Block [ESI Cache](https://symfony.com/doc/current/http_cache/esi.html) and Block [SSI Cache](https://symfony.com/doc/4.4/http_cache/ssi.html) use features more related to symfony http cache than [symfony cache](https://symfony.com/doc/current/components/cache.html).
* I think the change should be done in two parts:
  * Make Page Bundle use [PSR-6](https://www.php-fig.org/psr/psr-6/) or [PSR-16](https://www.php-fig.org/psr/psr-16/) Cache Interface to store rendered blocks if wanted. (What Cache PSR should be prefered?) Symfony Cache is only an implementation of these two.
  * Make the ESI/SSI Cache be able use the previous PSR-6/16 cached page content and wrap it into ESI/SSI

i don't know yet how it is controlled which pages/blocks are cached in which way.

I need to say that i didn't used page bundle yet, so that's just my thoughts of uninvolved.

**Comment by eerison** [comment]
> I did some brain storming about Removing Sonata Cache(Bundle) from Page Bundle.
> 
> * Block [ESI Cache](https://symfony.com/doc/current/http_cache/esi.html) and Block [SSI Cache](https://symfony.com/doc/4.4/http_cache/ssi.html) use features more related to symfony http cache than [symfony cache](https://symfony.com/doc/current/components/cache.html).
> * I think the change should be done in two parts:
>   
>   * Make Page Bundle use [PSR-6](https://www.php-fig.org/psr/psr-6/) or [PSR-16](https://www.php-fig.org/psr/psr-16/) Cache Interface to store rendered blocks if wanted. (What Cache PSR should be prefered?) Symfony Cache is only an implementation of these two.
>   * Make the ESI/SSI Cache be able use the previous PSR-6/16 cached page content and wrap it into ESI/SSI
> 
> i don't know yet how it is controlled which pages/blocks are cached in which way.
> 
> I need to say that i didn't used page bundle yet, so that's just my thoughts of uninvolved.

what do you mean "Make Page Bundle uses PSR-6"? implement something or just make it uses : https://symfony.com/doc/current/components/cache.html#cache-contracts-versus-psr-6 ?

**Comment by Hanmac** [comment]
yeah that's another interface i could bind check.
I think we should prefer that one over the others because it has callbacks

**Comment by eerison** [comment]
> yeah that's another interface i could bind check. I think we should prefer that one over the others because it has callbacks

if you prefer do this ticket in 2 part it's fine, I guess it's better to review :) 

can you open a DRAFT pull request when you do something :)

**Comment by Hanmac** [comment]
one thing i didn't found yet, is it configurable what pages/blocks are cached and how long?

or should i try to add such option? (per page/block?)

**Comment by eerison** [comment]
> one thing i didn't found yet, is it configurable what pages/blocks are cached and how long?
> 
> or should i try to add such option? (per page/block?)

I guess it's fine you add the option, if it's easiest for you :) 

just remember that you need to add a default value for whom didn't add any configuration.

**Comment by Hanmac** [comment]
there is also https://twig.symfony.com/doc/3.x/tags/cache.html for doing caching of block/page segments

i need to understand the structure of block/page in sonata better, but in theory we could use symfony cache to check if a rendered block/page already exist, so no database is needed for blocks and pages with non static id?

then for some static blocks we could use twig cache too (if needed?)

and last thing we could add esi/ssi cache, which could use the symfony cached rendered data too.

For the symfony Cache, it shouldn't be a problem to invalidate the data over their tags.
For Twig Cache the recommendation suggest to use `updated_at` as part of the cache item id


otherwise it might be cleaner to remove the caching from this Bundle, and add it alter again via other features (above)

some checking in the code, there are some hard coded dependencies that can made into soft-coded ones (like disabling the cache manager) or not defining the services. PageBundle should work even without caching. We could try that first before removing Caching in Major version.

**Comment by eerison** [comment]
Remove cache part 1 was solved here: #1427 🥳 

it's just missing remove the code from 4.x branch 😃

**Comment by Hanmac** [comment]
should i wait until SonataCI does merge 3.x into 4.x?

**Comment by Hanmac** [comment]
I did a PR for removing Cache in 4.x https://github.com/sonata-project/SonataPageBundle/pull/1430

i can rebase the PR if needed

**Comment by jordisala1991** [comment]
Yes, better to wait for the merge.
