### ISSUE TITLE
Add ability to choose site for dynamic/hybrid page

### ISSUE THREAD

**Issue by haivala** [sonata-project/SonataPageBundle#1610]
## Feature Request

When you create new dynamic page with symfony route and running `update-core-routes` the page is created for all of the defined sites. It would be nice to have ability to choose the site the page would be created on so that not all of the sites have the page in question.
Implementation could be done by adding route parameter to the symfony route and check it when `update-core-routes` is run.

Front Controller needs to take this in to account so that it does not show the error "please run update-core-routes" instead it would show 404 even though the symfony route exists.

Thoughts?

**Comment by jordisala1991** [comment]
It also happens for hybrid pages right?

I mean hybrid and dynamic are almost the same, just dynamic have also parameters on the route.

**Comment by haivala** [comment]
> It also happens for hybrid pages right?
> 
> I mean hybrid and dynamic are almost the same, just dynamic have also parameters on the route.

Yes as they are the same: They have Symfony route.

**Comment by haivala** [comment]
We should keep this?

**Comment by VincentLanglet** [comment]
> We should keep this?

That depends.
The github-actions stale bot has the purpose of closing old/staling issues. As an example with this issue, it's been opened for 6 months, without any activity, nobody else interested in this feature, and nobody providing PR. We, as maintainer, have limited time, and are now focusing on maintaining existing code rather than introducing new feature so there is little chance we work on this issue by ourself. 

If someone plan to provide a PR we should keep this. If not, I don't see real reason to keep a stale issue opened.
