### ISSUE TITLE
HostPathByLocale and HostPathSiteSelector cause redirection issues in dev mode

### ISSUE THREAD

**Issue by jasperdcbe** [sonata-project/SonataPageBundle#444]
Hi, I ran into a redirect issue when using either the "host_with_path" or "host_with_path_by_locale" multi-site settings.

The problem is that these two settings in HostPathByLocaleSiteSelector.php and HostPathSiteSelector.php use $site->getUrl() to redirect the request to the default website if it's available.

When looking at \Sonata\PageBundle\Model\Site::getUrl() you will notice that the construction of the URL is done without keeping in mind there might be a app_dev.php that has to be included in the URL. So when in dev mode you end up on app.php instead of app_dev.php

Code: 
https://github.com/sonata-project/SonataPageBundle/blob/master/Model/Site.php#L107

What would be a better way to build the URL here? I can create a PR if someone can point me in the right direction :)

**Comment by vworldat** [comment]
Can confirm this. It also affects some other sonata blocks that use $site->getUrl(), such as the default breadcrumb block.

**Comment by jordisala1991** [comment]
You htaccess or apache vhost or nginx config should handle the app_dev or app so you dont have to include it in the url.

IMO this is an issue with the configuration and should not be fixed here. On Sf 4 there are not app or app_dev, only index.php. So that wont be needed anymore.

Closing. If you still think this is a problem that Sonata should fix, please ping me to discuss it.
