### ISSUE TITLE
page entity customize

### ISSUE THREAD

**Issue by nomadx** [sonata-project/SonataPageBundle#481]
Hello, i was added in Page entity media field, then this field used in  base layout. When i open home page by anonymous user, I get:

An exception has been thrown during the rendering of a template ("Warning: call_user_func_array() expects parameter 1 to be a valid callback, class 'Application\Sonata\PageBundle\Entity\Page' does not have a method 'media'") in base_layout.html.twig at line 63.

But when i login by admin user and open home page it's ok. 

Any help much appreciated.

**Comment by Charlewic** [comment]
Hi, 

Same problem here (trying to add extra attribute to the Page entity)

Nomadx I can explain the reason of the problem, but, I can't resolve it.

When you are logged with your Admin user the system give you Page entities, so any of your extra attributes is here.
But, when you are unlogged the system doesn't provide the page (because the page can have be changed) so he passed the last snapshot (classe SnapshotPageProxy). And the snapshot doesn't know anything about your page custom attribute.

If you look closely to the snapshot table you will see that the snapshot store the page's attributes in a JSON object (column content). So when he print the page to an unlogged user the system never load the page but create an object from this JSON object.

The system have to handle with this extra attributes to add them to this JSON data : it could be an extend to the function who create the snapshot or something else.

By the way, if anything like this exist, please explain it to me, because I found nothing on it in the documentation.

Finally I'd like to say that you have done a really great job on these bundles.
Please continue like this !!

**Comment by Charlewic** [comment]
Ok I found it !

Like I say, extra attributes in the Page entity are not managed by the snapshot system.

You have to help it. My solution is base on the override of the Transformer Class (Sonata\PageBundle\Entity\Transformer).

**Step 1 : Create your own Transformer Class (wherever you want, mine is in my Page bundle : Application\Sonata\PageBundle\Entity\UpgradeTransformer)**

**Step 2 : Make sure that you extend the transformer class :**

`class UpgradeTransformer extends Transformer{ ...`

**Step 3 : Override the good methods :**  
There is 2 methods in our case : create & load.  
Create will create the snapshot from a Page  
Load will create a page from a snapshot.

You don't have to copy the existing functions, be smart and use the parent:: methods.

**Step 4 : Tell to symfony to use your class and not the Sonata's Transformer Class**

To do that go in your config.yml and add this line :

```
parameters:
    locale: fr
#    Overide transformer service definition
    sonata.page.transformer.class: Application\Sonata\PageBundle\Entity\UpgradeTransformer
```

As you see, you have to change the file associated to the **sonata.page.transformer.class** service.

And voilà !!

To help you this is my full Transformer Class :

```
<?php
namespace Application\Sonata\PageBundle\Entity;

use Sonata\PageBundle\Entity\Transformer;
use Sonata\BlockBundle\Model\BlockInterface;
use Sonata\BlockBundle\Model\BlockManagerInterface;
use Sonata\PageBundle\Model\PageInterface;
use Sonata\PageBundle\Model\PageManagerInterface;
use Sonata\PageBundle\Model\SnapshotInterface;
use Sonata\PageBundle\Model\SnapshotManagerInterface;
use Sonata\PageBundle\Model\SnapshotPageProxy;
use Sonata\PageBundle\Model\TransformerInterface;
use Symfony\Bridge\Doctrine\RegistryInterface;

class UpgradeTransformer extends Transformer
{

    /**
     * {@inheritdoc}
     */
    public function create(PageInterface $page)
    {
        /** @var Page $page */
        $snapshot = parent::create($page);

        $content = $snapshot->getContent();
        $content['articleLanguage'] = $page->getArticleLanguage();
        $content['pageSummary'] = $page->getPageSummary();
        $content['publicationDate'] = $page->getPublicationDate();

        $snapshot->setContent($content);

        return $snapshot;
    }

    /**
     * {@inheritdoc}
     */
    public function load(SnapshotInterface $snapshot)
    {
        /** @var Page $page */
        $page = parent::load($snapshot);

        $content = $this->fixPageContent($snapshot->getContent());

        if(isset($content['articleLanguage'])){
            $page->setArticleLanguage($content['articleLanguage']);
        }
        if(isset($content['pageSummary'])){
            $page->setPageSummary($content['pageSummary']);
        }
        if(isset($content['publicationDate'])){
            $page->setPublicationDate($content['publicationDate']);
        }

        return $page;
    }
}
```
