### ISSUE TITLE
Super admin is not an Page Editor

### ISSUE THREAD

**Issue by Neodork** [sonata-project/SonataPageBundle#623]
Hello again,

When browsing around in the Page bundle I noticed the super admin will never receive Page Editor functions. This is a bother to the super admin.

``` php
   // CmsManager/CmsManagerSelector.php

   // ...

    /**
     * @param InteractiveLoginEvent $event
     */
    public function onSecurityInteractiveLogin(InteractiveLoginEvent $event)
    {
        if ($this->getSecurityContext()->getToken() && ($this->getSecurityContext()->isGranted('ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT')
            || $this->getSecurityContext()->isGranted('ROLE_SUPER_USER'))) {
            $this->getSession()->set('sonata/page/isEditor', true);
        }
    }

    // ...

```

I will leave an PR when we agree on the solution.

**Comment by gremo** [comment]
I'm on mobile phone right now and I can't check, but I was working on this today. It's because in admin services the ROLE_SUPER_ADMIN has all roles by default (even if the role actualy dosn't exist). Symfony auth checker checks if the role exists, and the CMS manager uses the security context and not the admin service. The admin service should be injected and used instead.
