### ISSUE TITLE
Unable to find template on 2.3.10

### ISSUE THREAD

**Issue by bartoszmalec** [sonata-project/SonataPageBundle#664]
Hi,

After you add some changes in PageAdminController on 2.3.10 version, composer page stopped working. I think it breaks BC.

2.3.10: https://github.com/sonata-project/SonataPageBundle/blob/2.3.10/Controller/PageAdminController.php#L97

2.3.9: https://github.com/sonata-project/SonataPageBundle/blob/2.3.10/Controller/PageAdminController.php#L97

I need to call in page admin service:
`[ setTemplate, [compose, SonataPageBundle:PageAdmin:compose.html.twig]]`

**Comment by Soullivaneuh** [comment]
2.x is not supported anymore. 3.0 is push to start a new version management.

2.3.10 was pushed by myself because some trailing commit was on old 2.3 branch without tag.

If the `2.3.10` version does not work for you, please go back to `2.3.9`.

The best for you would be to upgrade to `3.0`.

Regards.
